###EschatologicalUnit.Statistics配置文件###
#该插件为OurWorld服务器EschatologicalUnit小游戏项目的一个原创插件
#信息控制插件

config:
  prefix: "[EschatologicalUnit]"   #插件提示消息的前缀
  cmd_pre_Wave:
  - say 不明物体正在靠近
  - title @a title {"text":"第%num%波","color":"red"}