###EschatologicalUnit.Statistics配置文件###
#该插件为OurWorld服务器EschatologicalUnit小游戏项目的一个原创插件
#信息控制插件

config:
  prefix: "[EschatologicalUnit]"   #插件提示消息的前缀
  EndWaveNum: 15   #总波数，达到这个波数，将结束游戏并生成战绩
  ReportDir: ./Eschatological_Unit/   #战绩报表存储位置
  cmd_pre_Wave:
  - say 不明物体正在靠近
  - title @a title {"text":"第%num%波","color":"red"}
  #对局开始时执行的指令
  cmd_first:
  - say 对局开始
  #对局结束后执行的指令
  cmd_last:
  - say 对局结束